remote_theme: aidswidjaja/just-the-docs
title: Adrian's Study Club
description: Resources and other cool stuff to help you prepare for your exams.
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
encoding: UTF-8
aux_links:
  "Email Adrian for help":
    - "mailto:sekolah@adrian.id.au?subject=[ASC Enquiry]"
footer_content: "Copyright &copy; 2017-2020  aidswidjaja and other contributors. CC BY-SA 4.0 Australia unless otherwise stated."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
show_gh_edit_link: true
gh_edit_repository: "https://github.com/aidswidjaja/study"
edit_link_text: "Edit this page on GitHub (request access first)"
color_scheme: "dark"
search_enabled: true
heading_anchors: true